# Generated by Django 5.2.6 on 2025-09-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120)),
                ('vapi_assistant_id', models.CharField(max_length=100, unique=True)),
                ('first_message', models.TextField()),
                ('system_prompt', models.TextField()),
                ('model_provider', models.CharField(default='anthropic', max_length=50)),
                ('model_name', models.CharField(default='claude-3-sonnet-20240229', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
