# Generated by Django 5.2.6 on 2025-09-24 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_type', models.CharField(max_length=120)),
                ('business_name', models.CharField(max_length=200)),
                ('agent_name', models.CharField(default='AVA', max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('website_url', models.URLField(blank=True)),
                ('welcome_prompt', models.TextField(default='Hi! How can I help you today?')),
                ('business_description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('embed_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('embed_secret', models.CharField(blank=True, max_length=64)),
                ('openai_api_key', models.CharField(blank=True, help_text='Optional per-agent key', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
